# Generated by Django 5.1.2 on 2024-10-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('vehicle_no', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=12)),
                ('wheel_type', models.CharField(choices=[('10 Wheel', '10 Wheel'), ('12 Wheel', '12 Wheel'), ('Others', 'Others')], max_length=20)),
            ],
        ),
    ]
