# Generated by Django 5.1.2 on 2024-10-31 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='vehicle_no',
        ),
        migrations.RemoveField(
            model_name='register',
            name='wheel_type',
        ),
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_type', models.CharField(choices=[('10 Wheel', '10 Wheel'), ('12 Wheel', '12 Wheel'), ('Others', 'Others')], max_length=20)),
                ('vehicle_no', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='Construction.register')),
            ],
        ),
    ]
