name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.12]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Staging environment only
      - name: Build the suits-backend docker image for Docker Hub Server
        if: github.ref == 'refs/heads/master' || (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master')
        run: docker build . --file Dockerfile --build-arg PORT=8000 --tag ${{ secrets.DOCKER_HUB_USERNAME }}/freelencing:latest

      - name: Push the suits-backend Staging docker image to Docker Hub
        if: github.ref == 'refs/heads/master' || (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master')
        run: docker push  ${{ secrets.DOCKER_HUB_USERNAME }}/freelencing:latest
